### ISSUE TITLE
Separate faz-bot into multiple repositories

### ISSUE THREAD

**Issue by FAZuH** [FAZuH/faz-bot-app-discord#81]
Been something I wanted to do, and would like to get it done with before faz-bot 1.0.

Separate faz-bot into:

## faz-utils
General utilities library. Includes:
 - Base modules: Heartbeat, database, API
 - Utility modules, such as Properties, CacheUtils, RetryHandler
## faz-bot-core
Core logic used by the other faz-bot components
 - Database implementation
 - Wynncraft API wrapper
 - Wynncraft utility modules
## faz-bot-app-discord
faz-bot Discord bot application
## faz-bot-app-collect
faz-bot application for Wynncraft data collection

# Tasks:
- [x] [python-faz-utils](https://github.com/FAZuH/python-faz-utils)
- [x] [python-faz-bot-core](https://github.com/FAZuH/python-faz-bot-core)
- [x] [faz-bot-app-collect](https://github.com/FAZuH/faz-bot-app-collect)
- [ ] [faz-bot-app-discord](https://github.com/FAZuH/faz-bot-app-discord)
